@startuml "C4_Container_Dataplatform"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!pragma layout smetana

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title Centric Dataplatform Container landscape with DataIku

Person_Ext(customer, "Gemeente", "Gemeente met behoefte voor dataplatform")

System_Ext(saas, "dataplatform", "Dataplatform SaaS service")

Enterprise_Boundary(dataplatform, "Dataplatform"){
    System_Boundary(dataikuA, "Gemeente A", "DataIku instance"){
      Container(fleetmanagerA, "Fleet Manager", "DataIku", "Facilitate deployment of DataIku cluster resources")
      Container(dssnodesA, "DSS nodes", "Azure AKS", "Nodes that run the DataIku software")
      ContainerDb(datapoolA, "Data pool","Microsoft SQL, Azure Datalake", "Holds data to build models")
    }
    System_Boundary(dataikuB, "Gemeente B", "DataIku instance"){
      Container(fleetmanagerB, "Fleet Manager", "DataIku", "Facilitate deployment of DataIku cluster resources")
      Container(dssnodesB, "DSS nodes", "Azure AKS", "Nodes that run the DataIku software")
      ContainerDb(datapoolB, "Data pool","Microsoft SQL, Azure Datalake", "Holds data to build models")
    }

}

Rel(fleetmanagerA, dssnodesA, "deploys", "ARM templates")
Rel(dssnodesA, datapoolA, "uses data from", "technology")
Rel(fleetmanagerB, dssnodesB, "deploys", "ARM templates")
Rel(dssnodesB, datapoolB, "uses data from", "technology")

footer drawn by Ilco Zeggelaar with PlantUML v. %version() and C4-PlantUML v. C4Version() 

@enduml