@startuml "Dataplatform"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml
!pragma layout smetana

LAYOUT_TOP_DOWN()
LAYOUT_WITH_LEGEND()

title Centric Dataplatform Deployment landscape with DataIku

Person_Ext(customer, "Gemeente", "Gemeente met behoefte voor dataplatform")

System(saas, "dataplatform", "Dataplatform SaaS service")

Enterprise_Boundary(dataplatform, "Dataplatform"){
 Deployment_Node(tenantA, "Customer Tenant", "Azure Tenant"){
  Deployment_Node(subscriptionA, "Subscription", "CSP"){
   System(dataikuA, "Gemeente A", "DataIku instance")
  }  
 }
 Deployment_Node(tenantB, "Customer Tenant", "Azure Tenant"){
  Deployment_Node(subscriptionB, "Subscription", "CSP"){
   System(dataikuB, "Gemeente B", "DataIku instance")
  }  
 }
 Deployment_Node(tenantC, "Customer Tenant", "Azure Tenant"){
  Deployment_Node(subscriptionC, "Subscription", "CSP"){
   System(dataikuC, "Gemeente C", "DataIku instance")
  }
 }
 Deployment_Node(tenantCentric, "Centric SaaS Tenant", "Azure Tenant"){
  Deployment_Node(subscriptionCentric, "Subscription", "MCA"){
   System(vasCentric, "Centric", "Value added services")
  }
 }
 Deployment_Node(subscriptionSaaS, "Subscription via MCA"){
  System(discovery, "Discovery/Share/Invite", "Centric developed service for integration")
 }
}

Rel(customer, saas, "Requests insights")
Rel_D(saas, discovery, "ask for discovery")
Rel(discovery, dataikuA, "Integration")
Rel(discovery, dataikuB, "Integration")
Rel(discovery, dataikuC, "Integration")
Rel(discovery, vasCentric, "Integration")

footer drawn by Ilco Zeggelaar with PlantUML v. %version() and C4-PlantUML v. C4Version() 

@enduml